### PR TITLE
Update example and dependencies.

### PR DESCRIPTION
**Pull request by mrstegeman**

### CODE REVIEW

**Comment by plietar** [comment]
Why move the example to its own directory?

**Comment by mrstegeman** [comment]
Just seems like good habit, especially if more examples are added. I can move back if you'd like.

**Comment by plietar** [comment]
Having it as is allows it to be run with `cargo run --example register`, which is nice.
I don't think this is possible with a separate `Cargo.toml`.

**Comment by mrstegeman** [comment]
Ah, fair enough.

**Comment by mrstegeman** [comment]
@plietar updated.

**Comment by plietar** [comment]
Sweet, thanks.

**Pull request merged**
